### ISSUE TITLE
About making local datasets

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#10]
I have a local dataset including only ```.jpg or .png``` images, I name it ```DataOri```. 

I want to use it to make image retrieval by making two folders: ```gallery and query```. The gallery folder has all original images of DataOri. And the query folder has some ```patches``` randomly made from the  DataOri, i.e. 0.5 scale size of the original image. Target: just use one query patches to search for top-k original images. 

Given the above two folders: ```gallery and query```, what should I do to quickly make this local dataset valid in this project and how to calculate metrics like mAP.

Appreciate your advice.

**Comment by hby96** [comment]
You can construct the gallery and query folders like CUB-200.

**Comment by HymEric** [comment]
Thank you : ). I will try.

**Comment by HymEric** [comment]
I found CUB-200 needs the class label and each class has many images just like caltech101. But I only have images and each image is can be viewed as a class. I have an idea, to make each image in one directory and placed as caltech101. This is work and I get a result. Do you have other opinions?

**Comment by hby96** [comment]
For your specific task, you can also write your own make_ds function and put it into pyretri/extract/utils/make_data_json.py
