### ISSUE TITLE
About the MAP problem in SCDA paper

### ISSUE THREAD

**Issue by mojie4321** [PyRetri/PyRetri#11]
Thank you very much for your code.I have a few questions about this code.Why can't MAP precision be achieved in SCDA paper.
Looking forward to your reply .

**Comment by hby96** [comment]
Because SCDA gives the top-k mAP, while we give the mAP.

**Comment by HymEric** [comment]
I'm also curious. In the SCDA paper,  each image in the testing set is treated as a query, and the training images are regarded as the gallery. The top-k mAP retrieval performance is reported. How to calculate them? And what your method to calculate? Could you explain this in detail? 

So appreciate your reply!
