### ISSUE TITLE
About local model module

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#12]
I added my own model as ```https://github.com/PyRetri/PyRetri/blob/master/docs/GETTING_STARTED.md```. But it needs more modification for my own module work. I have made others changes and got the features by running ```extract_feature.py```. But I encountered this problem when running ```python3 main/index.py -cfg configs/my_own_local.yaml```. Can you help me?

![image](https://user-images.githubusercontent.com/26487821/86310275-3d4bba00-bc50-11ea-8271-8df851d4f9b0.png)

**Comment by HymEric** [comment]
I have addressed it.

**Comment by clarkkent0618** [comment]
Hi！ How do you solve the problem? Thank you very much
