### ISSUE TITLE
How to evaluate with original model feature output?

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#13]
If I want to use the original feature output to make evaluation of image retrieve as the baseline, which means we do not use the  Feature Representation and Post-processing. How to do that? 

Thank you.

**Comment by hby96** [comment]
You can simply set the aggregators as "GAP" and set the dim_processors as "Identity".

**Comment by HymEric** [comment]
Thanks. It can work. But why can't set aggregator as none or delete it directly?

**Comment by hby96** [comment]
Because we need to aggregate several descriptors into a global descriptor to measure the similarity between images. In addition, the aggregation methods provided by us would not do any process on 2-dimention features, so you can directly use them :)

**Comment by HymEric** [comment]
cool! However, when I plan to search for feature extraction. Something wrong, 
![image](https://user-images.githubusercontent.com/26487821/86506791-75482e00-be05-11ea-9431-1ff4aa2072d9.png)

It's about config key, could you tell me where to set it?

**Comment by hby96** [comment]
What is “simclr”?

**Comment by HymEric** [comment]
I add a model in the ```pyretri\models\backbone\backbone_impl\simclr.py``` and I want to search a good hyper-params. So, I add my model and extractor in the ```search\search_modules\extract_dict.py``` like:
![image](https://user-images.githubusercontent.com/26487821/86506973-f18f4100-be06-11ea-8227-31e1588e8454.png)

**Comment by HymEric** [comment]
It seems like my model name does not appear when run ```pyretri.config.get_defaults_cfg.py```

**Comment by hby96** [comment]
Have you imported “simclr” in init file like this?

**Comment by HymEric** [comment]
Do you mean add this in ```pyretri\models\backbone.__init__.py```:

```python
from .backbone_impl.resnet import ResNet
from .backbone_impl.vgg import VGG
from .backbone_impl.reid_baseline import ft_net
from .backbone_impl.simclr import SimCLR
from .backbone_base import BackboneBase


__all__ = [
    'BackboneBase',
    'ResNet', 'VGG',
    'ft_net',
    'SimCLR',
]
```

I have added this.

**Comment by hby96** [comment]
But your name here is "SimCLR" not "simclr".

**Comment by HymEric** [comment]
I just add it according to ```ResNet```, in ```resnet.py``` the class is ResNet and there are resnet50, resnet101 fun et.al. In my simclr.py the class is SimCLR and there is simclr func. So, I think there are other problems.

**Comment by hby96** [comment]
Have you import the backbone and register your model like this?

**Comment by HymEric** [comment]
yes. as you see.
![image](https://user-images.githubusercontent.com/26487821/86507531-754b2c80-be0b-11ea-927e-d58f6601e990.png)

**Comment by HymEric** [comment]
Thank you very much. I have found the problem.

**Comment by hby96** [comment]
It’s so strange. 

I add a model to evaluate the code is right just now.

Are you sure all your changes are in effect? May you should re-install PyRetri locally since you have add new components in this library?

**Comment by hby96** [comment]
So what's the problem? I am curious.

**Comment by HymEric** [comment]
Yes. You are right. The changes do not in effect before.

**Comment by HymEric** [comment]
Now, I also have another question. Is this logs right？
![image](https://user-images.githubusercontent.com/26487821/86507903-34a0e280-be0e-11ea-93f9-703c50702ca1.png)

**Comment by hby96** [comment]
It’s right because your feature is N*C, not N*C*H*W.

**Comment by HymEric** [comment]
It likes it skip all aggregators? Is this ok? Can you give some ideas to do image retrieval and search good hyper-parmas methods with N*C?

**Comment by hby96** [comment]
N*C feature can not be aggregated since it is already a global feature. I think dim_process is important like PCA or SVD. In addition, feature enhance is useful in image retrieval and you can try these methods we provided.

**Comment by HymEric** [comment]
Thanks for your suggestions! : ) 

And the GAP or other aggregators will not do anything on this N*C features. So, this doesn't matter if I use GAP for it does need one op in aggregation. Is this right?

**Comment by hby96** [comment]
Yes, you’re right.

**Comment by HymEric** [comment]
I'm curious if the aggregators don't work. Why I got this? The different aggregator has different performance.
![image](https://user-images.githubusercontent.com/26487821/86508816-96187f80-be15-11ea-9e32-8c0ac70fc797.png)

**Comment by HymEric** [comment]
And every time I run ```python main/index.py -cfg configs/pattern_simclr.yaml``` with ```pca_whiten```, the result is different. Is this because of the training phase in PCA?

**Comment by hby96** [comment]
Maybe you should check your config, I can’t find where goes wrong based on the information you give.
