### ISSUE TITLE
mAP

### ISSUE THREAD

**Issue by zdxy** [PyRetri/PyRetri#23]
按照提供的预训练模型和数据集跑出的mAP特别低，我完全是按照指引的步骤运行的。还有就是OXford数据集的指标部分，一直报找不到gt文件，换成绝对路径也不行。请问是哪里出了问题吗
``[LoadFeature]: loading feature from /home/ubuntu/CBIR/PyRetri/data/features/caltech/query01/part_0.json...
[LoadFeature] Success, total 4310 images,
 feature names: dict_keys(['pool5_GeM'])
[LoadFeature]: loading feature from /home/ubuntu/CBIR/PyRetri/data/features/caltech/gallery01/part_0.json...
[LoadFeature] Success, total 4367 images,
 feature names: dict_keys(['pool5_GeM'])
[LoadFeature] Success, total 4367 images,
 feature names: dict_keys(['pool5_GeM'])
--------------- Retrieval Evaluation ------------
mAP: 1.1
R@1: 0.0        R@2: 0.1        R@4: 0.1        R@8: 0.3

**Comment by hnzjuer** [comment]
The same for me!! 
The result of mAP is low...Any questions?
---------------------------------------------------------------------------------------------------
$ python main/index.py -cfg configs/oxford.yaml 
[LoadFeature]: loading feature from data/features/oxford/query/part_0.json...
[LoadFeature] Success, total 55 images, 
 feature names: dict_keys(['pool5_GAP'])
[LoadFeature]: loading feature from data/features/oxford/gallery/part_0.json...
[LoadFeature]: loading feature from data/features/oxford/gallery/part_1.json...
[LoadFeature] Success, total 5063 images, 
 feature names: dict_keys(['pool5_GAP'])
[LoadFeature]: loading feature from data/features/oxford/gallery/part_0.json...
[LoadFeature]: loading feature from data/features/oxford/gallery/part_1.json...
[LoadFeature]: loading feature from data/features/oxford/query/part_0.json...
[LoadFeature] Success, total 5118 images, 
 feature names: dict_keys(['pool5_GAP'])
--------------- Retrieval Evaluation ------------
mAP: 1.2
R@1: 0.0	R@2: 0.0	R@4: 3.6	R@8: 5.5

**Comment by hby96** [comment]
Do you use the right pre-trained model?

**Comment by zdxy** [comment]
> Do you use the right pre-trained model?

Thank you for your reminder！now, the result is consistent with the presentation！

**Comment by Wu-Jin-tao** [comment]
can I know how do you solve this problem?
