### ISSUE TITLE
feature extraction issue for vgg model

### ISSUE THREAD

**Issue by weidezhang** [PyRetri/PyRetri#29]
Hi 

When I downloaded the vgg16_hybrid1365.pt model and do feature_extraction on oxford dataset. I found the shape mismatch error.  Any idea why? Thank you, 

python3 main/extract_feature.py -dj oxford_query.json -sp ~/Downloads/oxford/features/query/ -cfg configs/oxford.yaml 
/Users/tslaqq/miniconda3/lib/python3.9/site-packages/torchvision-0.9.1-py3.9-macosx-10.9-x86_64.egg/torchvision/transforms/transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
[LoadStateDict]: shape mismatch in parameter classifier.6.bias, torch.Size([1000]) vs torch.Size([1365])
[LoadStateDict]: shape mismatch in parameter classifier.6.weight, torch.Size([1000, 4096]) vs torch.Size([1365, 4096])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'classifier.6.weight', 'classifier.6.bias'}
  0%|

**Comment by weidezhang** [comment]
it seems it's due to the mismatch between vgg16 and vgghybrid.

**Comment by weidezhang** [comment]
I fixed the issue. now the issue is in single_index.py, it seems it complains pool5_GAP not in dict_keys

**Comment by A-hardworking-people** [comment]
can I know how do you fix the above mention problem, thank you very much！

**Comment by jhchan0805** [comment]
How did you solved for this problem? @weidezhang I am using the pretrained **vgg16_hybrid1365** model
