### ISSUE TITLE
Questions about constructing Oxford5k dataset

### ISSUE THREAD

**Issue by lizongnan** [PyRetri/PyRetri#3]
Hello, there are two questions about constructing Oxford5k dataset:
├── cbir
│   ├── oxford
│   │   ├── gt
│   │   │   ├── all_souls_1_good.txt
│   │   │   └── ··· 
│   │   └── images
│   │       ├── all_souls_000000.jpg
│   │       └── ··· 
│   └── pairs
│       ├── gt
│       │   ├── **defense_1_good.txt**
│       │   └── ··· 
│       └── images
│           ├── defense
│           │   ├── paris_defense_000000.jpg
│           │   └── ··· 
│           └── ··· 
1. How to determine the name of the folder containing groundtruth files and images? In other words, how do I know groundtruth files and corresponding images should be placed in the directory: oxford, pairs and any others?
2. 'defense_1_*.txt' is not included in groundtruth files 'gt_files_170407.tgz'. [https://www.robots.ox.ac.uk/~vgg/data/oxbuildings/](url)

Looking forward to your answer， thanks!

**Comment by hby96** [comment]
Hi~

The oxford5k and paris are two independent datasets.

oxford5k URL: https://www.robots.ox.ac.uk/~vgg/data/oxbuildings/
paris URL: https://www.robots.ox.ac.uk/~vgg/data/parisbuildings/

So for question 1: what dataset did you download, you put it in the corresponding folder. For example, if you download the images and gt files of oxford5k, you should put them in oxford. If you download the images and gt files of paris, you should put them in paris.

As for question 2: you should go to the paris URL to download the images and gt files of paris dataset. 'defense_1_*.txt' is included in groundtruth file 'paris_120310.tgz'.

Hope my answer can help you~

**Comment by lizongnan** [comment]
I got it, thanks a lot~
