### ISSUE TITLE
use extract_feature.py extract indoor dataset feature.Model and state_dict portion miss match.Is that right?

### ISSUE THREAD

**Issue by JH95-ai** [PyRetri/PyRetri#35]
Command lines is:
python extract_feature.py -dj ../data_jsons/indoor_gallery.json -sp ../data/features/indoor/gallery/ -cfg  ../configs/indoor.yaml

/data/places365_model/res50_places365.pt use [https://drive.google.com/open?id=1lp_nNw7hh1MQO_kBW86GG8y3_CyugdS2](url)

and Model and state_dict portion miss match 

> `[LoadStateDict]: shape mismatch in parameter fc.weight, torch.Size([1000, 2048]) vs torch.Size([365, 2048])
[LoadStateDict]: shape mismatch in parameter fc.bias, torch.Size([1000]) vs torch.Size([365])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'layer2.0.downsample.1.num_batches_tracked', 'layer2.3.bn1.num_batches_tracked', 'layer2.1.bn3.num_batches_tracked', 'layer3.0.bn1.num_batches_tracked', 'layer4.0.bn1.num_batches_tracked', 'layer3.4.bn2.num_batches_tracked', 'layer4.1.bn1.num_batches_tracked', 'layer3.4.bn1.num_batches_tracked', 'layer4.0.bn3.num_batches_tracked', 'layer2.2.bn3.num_batches_tracked', 'layer1.2.bn2.num_batches_tracked', 'layer2.0.bn2.num_batches_tracked', 'layer1.1.bn1.num_batches_tracked', 'layer4.0.bn2.num_batches_tracked', 'layer3.1.bn3.num_batches_tracked', 'layer3.1.bn1.num_batches_tracked', 'layer1.2.bn1.num_batches_tracked', 'layer2.2.bn2.num_batches_tracked', 'layer4.2.bn2.num_batches_tracked', 'layer1.0.downsample.1.num_batches_tracked', 'layer3.0.bn3.num_batches_tracked', 'layer3.3.bn2.num_batches_tracked', 'layer3.2.bn2.num_batches_tracked', 'layer2.2.bn1.num_batches_tracked', 'layer1.1.bn2.num_batches_tracked', 'layer3.5.bn1.num_batches_tracked', 'layer3.4.bn3.num_batches_tracked', 'layer4.2.bn3.num_batches_tracked', 'layer4.2.bn1.num_batches_tracked', 'layer1.0.bn2.num_batches_tracked', 'layer2.1.bn1.num_batches_tracked', 'layer2.3.bn3.num_batches_tracked', 'layer2.0.bn1.num_batches_tracked', 'layer1.0.bn3.num_batches_tracked', 'layer1.0.bn1.num_batches_tracked', 'layer3.0.bn2.num_batches_tracked', 'layer3.5.bn2.num_batches_tracked', 'layer4.0.downsample.1.num_batches_tracked', 'layer4.1.bn3.num_batches_tracked', 'bn1.num_batches_tracked', 'layer3.2.bn1.num_batches_tracked', 'layer1.1.bn3.num_batches_tracked', 'fc.bias', 'layer3.3.bn1.num_batches_tracked', 'layer1.2.bn3.num_batches_tracked', 'layer2.3.bn2.num_batches_tracked', 'layer3.0.downsample.1.num_batches_tracked', 'layer3.2.bn3.num_batches_tracked', 'layer3.5.bn3.num_batches_tracked', 'layer2.1.bn2.num_batches_tracked', 'layer3.3.bn3.num_batches_tracked', 'layer3.1.bn2.num_batches_tracked', 'fc.weight', 'layer2.0.bn3.num_batches_tracked', 'layer4.1.bn2.num_batches_tracked'}
`

**Comment by JH95-ai** [comment]
/data/places365_model/res50_places365.pt use https://drive.google.com/file/d/1lp_nNw7hh1MQO_kBW86GG8y3_CyugdS2/view

**Comment by jhchan0805** [comment]
How do you solved for this shape mismatch problem? @NeekHua
