### ISSUE TITLE
where is paris_split.txt?

### ISSUE THREAD

**Issue by chenhaocs** [PyRetri/PyRetri#6]
To interface the pertained model on Oxford dataset,  features are needed to be extracted from Paris dataset.
So splitting Paris dataset is also required, right?

**Comment by hby96** [comment]
Hi~

For Paris dataset, we directly extract features of all the Paris dataset images and use these features to train PCA of Oxford dataset. 

So splitting Paris dataset is not required, you just need to extract features of all Paris dataset images.

**Comment by chenhaocs** [comment]
> Hi~
> 
> For Paris dataset, we directly extract features of all the Paris dataset images and use these features to train PCA of Oxford dataset.
> 
> So splitting Paris dataset is not required, you just need to extract features of all Paris dataset images.

Thanks for your quick reply!

**Comment by prathmeshrmadhu** [comment]
Hi, 

Can you help me how do you generate the features without split file?
