### ISSUE TITLE
Loads empty dataloader for Oxford5k dataset

### ISSUE THREAD

**Issue by prathmeshrmadhu** [PyRetri/PyRetri#7]
Hi,

Thanks for the code. Very cool work. I was trying to reimplement for the oxford 5k data. 
I followed the following steps : 
a) Setup the data structures/folders using the `install.md` file.
b) Generate the split-files.
c) Now, the next I am trying to do is generate the features using `extract_features.py` and somehow my dataloader is empty. Can you help me here?

Things I tried:
1) I tried changing the `folder; name` on line 12-13 in `oxford.yaml` file. But that throws the `AssertionError` with respect to the registry. 
2) I have tried debugging it line by line. Attacheing the screenshots. 
<img width="695" alt="ss1" src="https://user-images.githubusercontent.com/16646533/83629792-088a0b80-a59b-11ea-8b91-8645990b5e7f.PNG">
<img width="757" alt="ss2" src="https://user-images.githubusercontent.com/16646533/83629800-09bb3880-a59b-11ea-9457-6bb9f5702ed4.PNG">

**Comment by hby96** [comment]
Hi~

Can you show me the original error message when you try to extract features? I have no idea wrong what's your exactly wrong with your codes. 

Have you made the data json files before extracting features?

**Comment by prathmeshrmadhu** [comment]
So, there was no error message. However, I think there were multiple smaller issues. 1) The path specified by me was `/data/cbir/oxford/images` as mentioned in the documentation. However, it was supposed to be `data/cbir/oxford/images`. After doing this, it went into the dataloader module.

After this, there was another issue of reading the images from `gallery` and `query` as they were links to the original images, so I had to change the relative paths within the folderBase and folder files in order to read from the original `images` folder. 

After this, I was able to generate the features now. However, I wanted to ask that the json generated is not `utf-8` encoded. Is that correct? I wanted to look at how the features are structured, if it's actually `utf-8` encoded, then may be I am making a mistake, if not then I probably might have to look into other ways.

**Comment by hby96** [comment]
The json file is not utf-8 encoded for saving time and space~

**Comment by A-hardworking-people** [comment]
can I know how do you fix the the following problem, thank you very much！
python3 main/extract_feature.py -dj data_jsons/oxford_query.json -sp data/features/oxford/query/ -cfg configs/oxford.yaml
[LoadStateDict]: shape mismatch in parameter classifier.6.bias, torch.Size([1000]) vs torch.Size([1365])
[LoadStateDict]: shape mismatch in parameter classifier.6.weight, torch.Size([1000, 4096]) vs torch.Size([1365, 4096])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'classifier.6.bias', 'classifier.6.weight'}
0it [00:00, ?it/s]
time: 0.31263256072998047

**Comment by A-hardworking-people** [comment]
**the problem has been:

$python3 main/extract_feature.py -dj data_jsons/oxford_gallery.json -sp data/features/oxford/gallery/ -cfg configs/oxford.yaml**

[LoadStateDict]: shape mismatch in parameter classifier.6.bias, torch.Size([1000]) vs torch.Size([1365])
[LoadStateDict]: shape mismatch in parameter classifier.6.weight, torch.Size([1000, 4096]) vs torch.Size([1365, 4096])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'classifier.6.weight', 'classifier.6.bias'}
  0%|                                                                                                                                                                                | 0/317 [00:00<?, ?it/s][DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/cornmarket_000018.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_002551.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_000487.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_003095.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/new_001080.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_001153.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_003672.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_000196.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/jesus_000134.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_000712.jpg'
Traceback (most recent call last):
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000349.jpg'
  File "main/extract_feature.py", line 52, in <module>
    main()
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000048.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/ashmolean_000287.jpg'
  File "main/extract_feature.py", line 48, in main
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_000228.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000602.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000329.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/worcester_000070.jpg'
    extract_helper.do_extract(dataloader, args.save_path, args.save_interval)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/extract/helper/helper.py", line 109, in do_extract
    for _, batch in zip(pbar, dataloader):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/folder/folder_impl/folder.py", line 78, in __getitem__
    img = self.transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/transformer/transformers_impl/transformers.py", line 107, in __call__
    return self.t_transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 198, in __call__
    return F.resize(img, self.size, self.interpolation)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 238, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'NoneType'>

  0%|                                                                                                                                                                                | 0/317 [00:00<?, ?it/s]
