### ISSUE TITLE
About dataset preparation

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#8]
It's a great job! But I encountered some problems.

After ```python main/split_dataset.py -d ./data/caltech101/ -sf main/split_file/caltech_split.txt```

In ```data/caltech101/gallery/accordion/``` there is the link not the image file

And when I run
```python main/extract_feature.py -dj data_jsons/caltech_gallery.json -sp ./data/features/caltech/gallery/ -cfg configs/caltech.yaml```
error happened

![image](https://user-images.githubusercontent.com/26487821/85262052-c66c2f80-b49f-11ea-92d8-0c1f96657b3a.png)

![image](https://user-images.githubusercontent.com/26487821/85261998-afc5d880-b49f-11ea-8bbc-388d5192c0ae.png)

**Comment by HymEric** [comment]
I have solved it by using the absolute path.

**Comment by hby96** [comment]
Thank you!

I have add some hint info in the docs.
