### ISSUE TITLE
Several findings maybe helpful

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#9]
With the ```Caltech101``` datasets, I found several little findings that may be helpful for you to perfect the great project. 

1. We should mkdir the ```data_jsons``` folder before making data json and mkdir ```retrieved_images``` before indexing a single image or error will happen. Maybe we can add the mkdir process into the related codes.
2. In the ```single_index.py``` 54 line should add .cpu()
```stacked_feature.append(img_fea_info[0][name].cpu()) # should add cpu()```

**Comment by hby96** [comment]
1. mkdir may be redundant since people may assign their own path to save the image and mkdir in the codes may cover the mistake that users forget to set the save path. So it's better not to add mkdir process into the related codes.

2. I have update the codes, thank you!
